jwt:
  secret: ${JWT_SECRET}
  expiration-access-in-milli-seconds: ${JWT_ACCESS_EXPIRATION}
  expiration-refresh-in-milli-seconds: ${JWT_REFRESH_EXPIRATION}

yandex:
  rasp:
    api:
      key: ${YANDEX_API_KEY}

spring:
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      ssl:
        enabled: ${REDIS_SSL_ENABLED}
      timeout: 20000
      connect-timeout: 10000

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    hikari:
      max-lifetime: 300000
      idle-timeout: 600000
      validation-timeout: 5000
      connection-timeout: 10000

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

cors:
  origin:
    allowed-patterns: ${CORS_ALLOWED_PATTERNS}